[package]
name = "ensodb"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
chrono = "0.4.42"
lru = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
